Javascript Capstone Project
Busiwa24/JS-Capstone-Project- pull request #32
Opened 2021-09-22 18:02 UTC by mbdesigns1989

In this PR we did ;
We used an API-based web app that displays Meals from the MealsDB API and the Involvement API from Microverse. 
The features of this web app include an option to like a meal by clicking on the like button A comment button that opens up a modal and allows users to leave comments.
We used ES6 modules,webpack.
Wrote units tests for a JavaScript app.
used Gitflow.
Performed a code review for each other.

2021-09-22 18:08 UTC, mbdesigns1989 commented
we have been working really hard on this project, we also repeated a week before so please approve us, we don't want to repeat the module, thanks.

2021-09-22 19:29 UTC, Emmyn5600 requested changes
## STATUS: CHANGES REQUESTED :recycle:

Hi, @mbdesigns1989  and @Busiwa24 

Great work on implementing the project requirements, however there are some issues to be solved before you get approved but you are almost there:muscle:. 
   
 - The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:
![rr3](https://user-images.githubusercontent.com/55635977/134409008-67223305-3f51-4ec5-936c-aa2191ef8d61.png)

- All tests are passing successfully:heavy_check_mark:
![rr2](https://user-images.githubusercontent.com/55635977/134408867-03984dda-3688-4278-92cf-98317e1ecd76.png)

Changes required :writing_hand:
 
  - Kindly, attach the loom video as required.
  - Please check the comment under the review.
  
  Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-09-22 19:29 UTC, Emmyn5600 commented on README.md
> +- at http://localhost:8080/
- [ ] The live link demo shouldn't be look this, kindly deploy the app to the GitHub page to get the live link demo instead of `localhost:portnumber`

2021-09-22 19:29 UTC, Emmyn5600 commented on README.md
> +- [Copy this link](https://github.com/mbdesigns1989/To-do-List/tree/To-Do-list-add-and-remove)
- [ ] There is a typo with this link you used link for To-DO-list, kindly attach the right link instead of this one.

2021-09-22 19:29 UTC, Emmyn5600 commented on README.md
> +
- [ ] Add `-` before the social media accs to look the same as we have in the first author.

2021-09-22 19:29 UTC, Emmyn5600 commented on README.md
> +
- [ ] Add a link that redirect us to the issues

2021-09-22 19:29 UTC, Emmyn5600 commented on src/__test__/counter.test.js
> +});
- [ ] Great work, tests are passing successfully.

2021-09-22 19:29 UTC, Emmyn5600 commented on src/__test__/commentCount.test.js
> +});
- [ ] Great work, tests are passing successfully.

2021-09-22 19:29 UTC, Emmyn5600 commented on src/commentPopup.css
> +}
- [ ] To the comment button, kindly add `cursor:pointer` to make it cursor

2021-09-22 19:29 UTC, Emmyn5600 commented on src/likesApi.js
> +};
- [ ]  To the Like button, kindly add `cursor:pointer` to make it cursor
- [ ] The like button doesn't work, it doesn't count the likes as well as display them on the screen
![rr1](https://user-images.githubusercontent.com/55635977/134408575-ad4ce16b-0be7-44c7-82eb-0a34ee71ff66.png)

2021-09-23 07:18 UTC, mbdesigns1989 commented
Hello, we made all the changes required, please when you open the live demo wait a minute and the web app will work fine, thanks.

2021-09-23 07:42 UTC, Emmyn5600 commented on README.md
> +- [Copy this link](https://github.com/mbdesigns1989/To-do-List/tree/To-Do-list-add-and-remove)
Well solved

2021-09-23 07:42 UTC, Emmyn5600 commented on README.md
> +
Well solved

2021-09-23 07:43 UTC, Emmyn5600 commented on README.md
> +
Well solved

2021-09-23 07:43 UTC, Emmyn5600 commented on src/__test__/counter.test.js
> +});
Well done

2021-09-23 07:44 UTC, Emmyn5600 commented on src/likesApi.js
> +};
Well solved

2021-09-23 07:44 UTC, Emmyn5600 commented on README.md
> +- at http://localhost:8080/
Well solved

2021-09-23 07:52 UTC, Emmyn5600 commented on src/commentPopup.css
> +}
Not yet solved

2021-09-23 08:12 UTC, Emmyn5600 approved these changes
Hi,

Good job so far! 👏🏼 @mbdesigns1989 and @Busiwa24 

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- You have descriptive Readme file:heavy_check_mark:
- Live link demo is working properly:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous reviewers.

 #### Optional suggestions
    
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-09-23 08:20 UTC, merged